spring.application.name=ideacrate-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/ideacrate_db
spring.profiles.active=local
# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update

spring.app.jwtExpirationMs=86400000